# Generated by Django 5.2.1 on 2025-06-21 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fotopaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='foto',
        ),
        migrations.AlterField(
            model_name='fotopaciente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotopaciente',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fotopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.paciente'),
        ),
    ]
